import { createHash, randomBytes } from 'crypto';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { networkInterfaces } from 'os';

interface EnvironmentSecrets {
  NEXTAUTH_SECRET: string;
  INTERNAL_SERVICE_TOKEN: string;
  ENCRYPTION_KEY: string;
}

/**
 * Generates a secure random hex string of specified length
 */
function generateSecureHex(bytes: number): string {
  return randomBytes(bytes).toString('hex');
}

/**
 * Validates that a secret meets security requirements
 */
function validateSecret(secret: string, name: string, expectedLength: number): boolean {
  if (!secret) {
    console.error(`❌ ${name} is empty or undefined`);
    return false;
  }
  
  if (secret.length !== expectedLength) {
    console.error(`❌ ${name} has incorrect length: ${secret.length}, expected: ${expectedLength}`);
    return false;
  }
  
  if (!/^[a-f0-9]+$/i.test(secret)) {
    console.error(`❌ ${name} is not a valid hexadecimal string`);
    return false;
  }
  
  return true;
}

/**
 * Detects if running in a containerized environment where secrets are pre-generated
 */
function isContainerEnvironment(): boolean {
  return process.env.DOCKER_CONTAINER === 'true' || existsSync('/.dockerenv');
}

/**
 * Gets the local IP address for development NEXTAUTH_URL
 */
function getLocalIpAddress(): string {
  const interfaces = networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name] ?? []) {
      // Skip internal and non-IPv4 addresses
      if (!iface.internal && iface.family === 'IPv4') {
        return iface.address;
      }
    }
  }
  return 'localhost'; // Fallback to localhost if no IP found
}

/**
 * Reads and parses .env.local file for local development
 */
function readEnvLocal(): Record<string, string> {
  const envPath = join(process.cwd(), '.env.local');
  try {
    const envContent = readFileSync(envPath, 'utf-8');
    const envVars: Record<string, string> = {};

    envContent.split('\n').forEach((line) => {
      const [key, value] = line.split('=');
      if (key && value) {
        envVars[key.trim()] = value.trim();
      }
    });

    return envVars;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return {};
    }
    throw error;
  }
}

/**
 * Writes environment variables to .env.local for local development persistence
 */
function writeEnvLocal(envVars: Record<string, string>): void {
  const envPath = join(process.cwd(), '.env.local');
  const envContent = Object.entries(envVars)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');

  writeFileSync(envPath, envContent + '\n', 'utf-8');
}

/**
 * Loads secrets from environment with local development fallback generation
 */
function loadSecrets(): EnvironmentSecrets {
  const secrets: EnvironmentSecrets = {
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET || '',
    INTERNAL_SERVICE_TOKEN: process.env.INTERNAL_SERVICE_TOKEN || '',
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || ''
  };

  const isContainer = isContainerEnvironment();
  
  if (isContainer) {
    console.log('🐳 Container environment detected - using pre-generated secrets');
    
    // In container environment, secrets should already be generated by Docker
    // Just validate they exist and are properly formatted
    const validationResults = [
      validateSecret(secrets.NEXTAUTH_SECRET, 'NEXTAUTH_SECRET', 128),
      validateSecret(secrets.INTERNAL_SERVICE_TOKEN, 'INTERNAL_SERVICE_TOKEN', 128),
      validateSecret(secrets.ENCRYPTION_KEY, 'ENCRYPTION_KEY', 64)
    ];
    
    if (!validationResults.every(Boolean)) {
      throw new Error('❌ Container environment has invalid or missing pre-generated secrets. Check Docker setup.');
    }
    
    console.log('✅ Pre-generated secrets validated successfully');
    return secrets;
  }

  // Local development environment - generate secrets if missing
  console.log('🏠 Local development environment detected');
  
  // Read existing .env.local values
  const envLocalVars = readEnvLocal();
  let needsGeneration = false;
  let keysGenerated: string[] = [];

  // Check if any secrets are missing or invalid, generate if needed
  if (!validateSecret(secrets.NEXTAUTH_SECRET, 'NEXTAUTH_SECRET', 128)) {
    // Check .env.local first
    if (envLocalVars.NEXTAUTH_SECRET && validateSecret(envLocalVars.NEXTAUTH_SECRET, 'NEXTAUTH_SECRET', 128)) {
      secrets.NEXTAUTH_SECRET = envLocalVars.NEXTAUTH_SECRET;
    } else {
      secrets.NEXTAUTH_SECRET = generateSecureHex(64); // 64 bytes = 128 hex chars
      needsGeneration = true;
      keysGenerated.push('NEXTAUTH_SECRET');
    }
  }

  if (!validateSecret(secrets.INTERNAL_SERVICE_TOKEN, 'INTERNAL_SERVICE_TOKEN', 128)) {
    // Check .env.local first
    if (envLocalVars.INTERNAL_SERVICE_TOKEN && validateSecret(envLocalVars.INTERNAL_SERVICE_TOKEN, 'INTERNAL_SERVICE_TOKEN', 128)) {
      secrets.INTERNAL_SERVICE_TOKEN = envLocalVars.INTERNAL_SERVICE_TOKEN;
    } else {
      secrets.INTERNAL_SERVICE_TOKEN = generateSecureHex(64); // 64 bytes = 128 hex chars
      needsGeneration = true;
      keysGenerated.push('INTERNAL_SERVICE_TOKEN');
    }
  }

  if (!validateSecret(secrets.ENCRYPTION_KEY, 'ENCRYPTION_KEY', 64)) {
    // Check .env.local first
    if (envLocalVars.ENCRYPTION_KEY && validateSecret(envLocalVars.ENCRYPTION_KEY, 'ENCRYPTION_KEY', 64)) {
      secrets.ENCRYPTION_KEY = envLocalVars.ENCRYPTION_KEY;
    } else {
      secrets.ENCRYPTION_KEY = generateSecureHex(32); // 32 bytes = 64 hex chars
      needsGeneration = true;
      keysGenerated.push('ENCRYPTION_KEY');
    }
  }

  // Handle NEXTAUTH_URL for development
  if (process.env.NODE_ENV === 'development' && !process.env.NEXTAUTH_URL) {
    if (!envLocalVars.NEXTAUTH_URL) {
      const localIp = getLocalIpAddress();
      envLocalVars.NEXTAUTH_URL = `http://${localIp}:3000`;
      needsGeneration = true;
      keysGenerated.push('NEXTAUTH_URL');
    }
  }

  if (needsGeneration) {
    // Persist secrets to .env.local for local development consistency
    try {
      const updatedEnvVars = {
        ...envLocalVars,
        NEXTAUTH_SECRET: secrets.NEXTAUTH_SECRET,
        INTERNAL_SERVICE_TOKEN: secrets.INTERNAL_SERVICE_TOKEN,
        ENCRYPTION_KEY: secrets.ENCRYPTION_KEY
      };

      writeEnvLocal(updatedEnvVars);
      console.log(`🔧 Generated new secrets for local development: ${keysGenerated.join(', ')}`);
      console.log('💾 Local development secrets persisted to .env.local');
    } catch (error) {
      console.warn('⚠️ Could not persist secrets to .env.local:', error);
      console.log('🔄 Secrets will be regenerated on next restart');
    }
  } else {
    console.log('✅ All secrets already present and valid');
  }

  return secrets;
}

/**
 * Ensures all required security keys are present and valid
 * This function should be called during application initialization
 * 
 * In container environments: validates pre-generated secrets
 * In local development: generates and persists secrets as needed
 */
export function ensureSecureKeys(): EnvironmentSecrets {
  console.log('🔐 Initializing security keys...');
  
  const secrets = loadSecrets();
  
  // Set the secrets in process.env for runtime access
  process.env.NEXTAUTH_SECRET = secrets.NEXTAUTH_SECRET;
  process.env.INTERNAL_SERVICE_TOKEN = secrets.INTERNAL_SERVICE_TOKEN;
  process.env.ENCRYPTION_KEY = secrets.ENCRYPTION_KEY;
  
  // Set NEXTAUTH_URL if needed for development
  if (process.env.NODE_ENV === 'development' && !process.env.NEXTAUTH_URL) {
    const envLocalVars = readEnvLocal();
    if (envLocalVars.NEXTAUTH_URL) {
      process.env.NEXTAUTH_URL = envLocalVars.NEXTAUTH_URL;
    }
  }
  
  console.log('✅ Security keys initialized and validated');
  return secrets;
}

// Standard environment variable validation
const requiredEnvVars = [
  'NEXTAUTH_URL'
  // DATABASE_URL is optional for SQLite - defaults to ./data/wolfmanager.db
] as const;

// Validate required environment variables (only during runtime, not during build)
export function validateRequiredEnvVars() {
  requiredEnvVars.forEach((envVar) => {
    if (!process.env[envVar]) {
      throw new Error(`Missing required environment variable: ${envVar}`);
    }
  });
}

// Only validate during actual runtime when the server is fully started
// Skip during build phase and initial server setup
if (typeof window !== 'undefined') {
  // Client-side: always validate
  validateRequiredEnvVars();
} else if (process.env.NODE_ENV !== 'test' && process.env.NEXT_PHASE !== 'phase-production-build') {
  // Server-side: only validate if we're in the production server phase
  // and the environment should be fully initialized
  if (process.env.NEXT_PHASE === 'phase-production-server') {
    validateRequiredEnvVars();
  }
  // Note: For Docker containers, NEXTAUTH_URL is provided via docker-compose environment
}

// Export environment configuration
export const env = {
  // NextAuth configuration
  NEXTAUTH_URL: process.env.NEXTAUTH_URL!,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET || '',
  
  // Database
  DATABASE_URL: process.env.DATABASE_URL!,
  
  // Internal services
  INTERNAL_SERVICE_TOKEN: process.env.INTERNAL_SERVICE_TOKEN || '',
  
  // Encryption
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || '',
  
  // Logging
  WOLF_LOG_LEVEL: process.env.WOLF_LOG_LEVEL || 'info',
  
  // Environment
  NODE_ENV: process.env.NODE_ENV || 'development',
  
  // Runtime flags
  IS_DEVELOPMENT: process.env.NODE_ENV === 'development',
  IS_PRODUCTION: process.env.NODE_ENV === 'production'
} as const;
