services:
  wolf-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /var/run/wolf:/var/run/wolf
    environment:
      - NODE_ENV=production 
