services:
  wolf-manager:
    image: ghcr.io/salty2011/wolf-manager:latest
    ports:
      - "3000:3000"
    volumes:
      - /var/run/wolf:/var/run/wolf
    environment:
      - NODE_ENV=production 
