services:
  wolf-manager:
    image: ghcr.io/salty2011/wolfmanager:main
    network_mode: host
    ports:
      - "9971:9971"
    volumes:
      - /var/run/wolf:/var/run/wolf
      - /games:/games
    environment:
      - NODE_ENV=production 
