version: '3.8'
services:
  wolf-manager:
    build: .
    ports:
      - "9971:9971"
    volumes:
      - ./config:/config
      - ${STEAM_LIBRARY_PATH}:/games:ro
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "wolf-manager"
        tag: "{{.Name}}" 
